"""introduce roles module

Revision ID: 5b05cdc443b8
Revises: 89c37c91c813
Create Date: 2025-12-03 21:35:05.368444

"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision: str = '5b05cdc443b8'
down_revision: Union[str, Sequence[str], None] = '89c37c91c813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

role_enum = postgresql.ENUM('student', 'teacher', 'admin', name='user_role_enum')


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_roles_slug')
    )
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)

    roles_table = table(
        'roles',
        column('id', postgresql.UUID(as_uuid=True)),
        column('slug', sa.String(length=50)),
        column('name', sa.String(length=100)),
        column('description', sa.String(length=255)),
        column('is_system', sa.Boolean()),
    )

    default_roles = [
        {
            'id': uuid.uuid4(),
            'slug': 'student',
            'name': 'Student',
            'description': 'Default student role',
            'is_system': True,
        },
        {
            'id': uuid.uuid4(),
            'slug': 'teacher',
            'name': 'Teacher',
            'description': 'Default teacher role',
            'is_system': True,
        },
        {
            'id': uuid.uuid4(),
            'slug': 'admin',
            'name': 'Administrator',
            'description': 'Default admin role',
            'is_system': True,
        },
    ]

    op.bulk_insert(roles_table, default_roles)

    role_map = {item['slug']: item['id'] for item in default_roles}

    op.add_column('users', sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key('fk_users_role_id_roles', 'users', 'roles', ['role_id'], ['id'])

    users_table = table(
        'users',
        column('role', role_enum),
        column('role_id', postgresql.UUID(as_uuid=True)),
    )
    connection = op.get_bind()
    enum_literal = lambda value: sa.literal(value, type_=role_enum)

    for slug, role_id in role_map.items():
        connection.execute(
            users_table.update()
            .where(users_table.c.role == enum_literal(slug))
            .values(role_id=role_id)
        )

    connection.execute(
        users_table.update()
        .where(users_table.c.role_id.is_(None))
        .values(role_id=role_map['student'])
    )

    op.alter_column('users', 'role_id', nullable=False)
    op.drop_column('users', 'role')
    role_enum.drop(connection, checkfirst=True)

    admin_users_table = table(
        'users',
        column('id', postgresql.UUID(as_uuid=True)),
        column('username', sa.String(length=150)),
        column('email', sa.String(length=255)),
        column('hashed_password', sa.String(length=255)),
        column('role_id', postgresql.UUID(as_uuid=True)),
        column('is_active', sa.Boolean()),
        column('is_verified', sa.Boolean()),
        column('must_change_password', sa.Boolean()),
        column('created_at', sa.DateTime(timezone=True)),
        column('updated_at', sa.DateTime(timezone=True)),
        column('last_login', sa.DateTime(timezone=True)),
    )

    admin_user_id = uuid.uuid4()
    timestamp = datetime.now(timezone.utc)

    op.bulk_insert(
        admin_users_table,
        [
            {
                'id': admin_user_id,
                'username': 'admin',
                'email': 'admin@example.com',
                'hashed_password': '$argon2id$v=19$m=65536,t=3,p=4$LWWMUapVqjWGsPbemzPmHA$yTVvrgATWn5iV2plM1yNcydrrWG7YUofOIAOO4ODvvI', # pwd 'is Admin123!'
                'role_id': role_map['admin'],
                'is_active': True,
                'is_verified': True,
                'must_change_password': False,
                'created_at': timestamp,
                'updated_at': timestamp,
                'last_login': None,
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    role_enum.create(connection, checkfirst=True)
    op.add_column('users', sa.Column('role', role_enum, server_default=sa.text("'student'::user_role_enum"), nullable=False))

    roles_table = table(
        'roles',
        column('id', postgresql.UUID(as_uuid=True)),
        column('slug', sa.String(length=50)),
    )
    users_table = table(
        'users',
        column('role', role_enum),
        column('role_id', postgresql.UUID(as_uuid=True)),
    )

    role_rows = connection.execute(sa.select(roles_table.c.id, roles_table.c.slug)).fetchall()
    for role_id, slug in role_rows:
        connection.execute(
            users_table.update().where(users_table.c.role_id == role_id).values(role=slug)
        )

    connection.execute(sa.text("DELETE FROM users WHERE username = 'admin'"))

    op.drop_constraint('fk_users_role_id_roles', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_column('users', 'role_id')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_table('roles')
    role_enum.drop(connection, checkfirst=True)
    # ### end Alembic commands ###
